apiVersion: v1
kind: ConfigMap
metadata:
  name: heartbeat
  namespace: kube-system
data:
  heartbeat.yml: |
  {{- .Values.config | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heartbeat
  namespace: kube-system
  labels:
    app: heartbeat
spec:
  selector:
    matchLabels:
      app: heartbeat
  template:
    metadata:
      labels:
        app: heartbeat
      annotations:
        checksum/secret: {{ toYaml .Values.config | sha256sum }}
    spec:
      containers:
      - name: heartbeat
        image: docker.elastic.co/beats/heartbeat:7.3.1
        imagePullPolicy: IfNotPresent
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        securityContext:
          runAsUser: 0
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: heartbeat-config
          mountPath: /usr/share/heartbeat/heartbeat.yml
          readOnly: true
          subPath: heartbeat.yml
        - name: data
          mountPath: /usr/share/heartbeat/data
      volumes:
      - name: heartbeat-config
        configMap:
          name: heartbeat
      - name: data
        hostPath:
          path: /var/lib/heartbeat
          type: DirectoryOrCreate
      terminationGracePeriodSeconds: 60