apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.appName }}-traefik
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    name: traefik
data:
  traefik.toml: {{ .Values.config | nindent 4 }}
    
