apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-traefik
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: {{ .Values.global.appName }}
    name: traefik
