apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-traefik
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 8080
    targetPort: 8080
    name: http-dashboard
  selector:
    app: {{ .Values.global.appName }}
    name: traefik
