global:
  appName: test
  namespace: default

minReplicas: 1
maxReplicas: 1
targetCPU: 60

resources:
  requests:
    memory: 200Mi
    cpu: "20m"
  limits:
    memory: 200Mi
    cpu: "400m"

config: |-
  output {
    stdout { }
  }  