global:
  appName: test
  namespace: default

minReplicas: 1
maxReplicas: 1
targetCPU: 60
targetMemory: 75

resources:
  requests:
    memory: 200Mi
    cpu: "20m"
  limits:
    memory: 200Mi
    cpu: "400m"

readinessProbe: |-
  tcpSocket:
    port: 5959
  initialDelaySeconds: 10
  periodSeconds: 10
  
livenessProbe: |-
  tcpSocket:
    port: 5959
  initialDelaySeconds: 120
  periodSeconds: 10

extraCmds: ""

environmentVariables:
  LOG_LEVEL: "info"
  XPACK_MONITORING_ENABLED: "false"

config: |-
  input { tcp { port => 5959 codec => json } }
  output { stdout { } }  