apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.appName }}-logstash
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    name: logstash
data:
  config: |
  {{- .Values.config | nindent 4 }}
    
