apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}-logstash
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    name: logstash
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
      name: logstash
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
        name: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:6.5.0          
          {{ if .Values.extraCmds }}
          command: ["/bin/sh"]
          args: ["-c", {{ .Values.extraCmds }} " && /usr/local/bin/docker-entrypoint"]
          {{ end }}          
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          livenessProbe: {{ tpl .Values.livenessProbe . | nindent 12 }}
          readinessProbe: {{ tpl .Values.readinessProbe . | nindent 12 }}
          {{- with .Values.environmentVariables }}
          env:
          {{- range $k, $v := . }}
          - name: {{ quote $k }}
            value: {{ quote $v }}
          {{- end }}
          volumeMounts:
          - mountPath: "/usr/share/logstash/pipeline"
            name: logstash-volume
      volumes:
      - name: logstash-volume
        configMap:
          name: {{ .Values.global.appName }}-logstash
          items:
          - key: config
            path: logstash.conf
