apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}-logstash
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.appName }}
    name: logstash
spec:
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
      name: logstash
  template:
    metadata:
      labels:
        app: {{ .Values.global.appName }}
        name: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:6.5.0
          command: ["/bin/sh"]
          args: ["-c","logstash-plugin install logstash-filter-prune && /usr/local/bin/docker-entrypoint"]
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: 5959
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 5959
            initialDelaySeconds: 120
            periodSeconds: 10
          env:
          - name: LOG_LEVEL
            value: "info"
          - name: XPACK_MONITORING_ENABLED
            value: "false"
          volumeMounts:
          - mountPath: "/usr/share/logstash/pipeline"
            name: logstash-volume
      volumes:
      - name: logstash-volume
        configMap:
          name: {{ .Values.global.appName }}-logstash
          items:
          - key: config
            path: logstash.conf
