apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.appName }}-logstash
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
  - port: 5959
    targetPort: 5959
    name: tcp
  selector:
    app: {{ .Values.global.appName }}
    name: logstash
