dependencies:
  - name: logstash
    version: 0.1.5
    repository: https://fmontezuma.github.io/helm-chart/
    condition: logstash.enabled
  - name: traefik
    version: 0.1.2
    repository: https://fmontezuma.github.io/helm-chart/
    condition: traefik.enabled