dependencies:
  - name: logstash
    version: 0.1.4
    repository: https://fmontezuma.github.io/helm-chart/
    condition: logstash.enabled
  - name: traefik
    version: 0.1.0
    repository: https://fmontezuma.github.io/helm-chart/
    condition: traefik.enabled