global:
  dnsSuffix: test.local  
  appName: nginx
  namespace: default

env: dev

dependenciesOnly: false

logstash:
  enabled: false

traefik:
  enabled: false

#replicaCount: 1
minReplicas: 1
maxReplicas: 5
targetCPU: 50
targetMemory: 75

progressDeadlineSeconds: 200

image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent

service:
  port: 80
  protocol: http
  additionalPorts: {}

ingress:
  enabled: true
  annotations: {}
  additionalRules: {}

environmentVariables: {}

readinessProbe: |-
  tcpSocket:
    port: {{ .Values.service.port }}
  initialDelaySeconds: 10
  periodSeconds: 10

livenessProbe: |-
  tcpSocket:
    port: {{ .Values.service.port }}
  initialDelaySeconds: 120
  periodSeconds: 10

resources: {}
lifecycle: {}
nodeSelector: {}
tolerations: []

affinity: |-
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - weight: 100
      podAffinityTerm:
        topologyKey: "failure-domain.beta.kubernetes.io/zone"
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "{{ .Values.global.appName }}"
    - weight: 99
      podAffinityTerm:
        topologyKey: "kubernetes.io/hostname"
        labelSelector:
          matchExpressions:
          - key: app
            operator: In
            values:
            - "{{ .Values.global.appName }}"
