dependencies:
  - name: ingress-nginx
    version: 0.1.1
    repository: https://fmontezuma.github.io/helm-chart/
  - name: dashboard
    version: 0.1.4
    repository: https://fmontezuma.github.io/helm-chart/
  - name: eks
    version: 0.1.1
    repository: https://fmontezuma.github.io/helm-chart/
  - name: autoscaler
    version: 0.1.0
    repository: https://fmontezuma.github.io/helm-chart/
  - name: istio
    version: 0.1.4
    repository: https://fmontezuma.github.io/helm-chart/
  - name: metrics-server
    version: 0.1.0
    repository: https://fmontezuma.github.io/helm-chart/
  - name: heapster
    version: 0.1.0
    repository: https://fmontezuma.github.io/helm-chart/
  - name: polaris
    version: 0.1.2
    repository: https://fmontezuma.github.io/helm-chart
  - name: filebeat
    version: 0.1.0
    repository: https://fmontezuma.github.io/helm-chart/
