dependencies:
  - name: ingress-nginx
    version: 0.1.4
    repository: https://fmontezuma.github.io/helm-chart/
  - name: dashboard
    version: 0.1.5
    repository: https://fmontezuma.github.io/helm-chart/
  - name: eks
    version: 0.1.1
    repository: https://fmontezuma.github.io/helm-chart/
  - name: autoscaler
    version: 0.1.1
    repository: https://fmontezuma.github.io/helm-chart/
  #- name: istio
  #  version: 0.1.8
  #  repository: https://fmontezuma.github.io/helm-chart/
  - name: metrics-server
    version: 0.1.0
    repository: https://fmontezuma.github.io/helm-chart/
  - name: heapster
    version: 0.1.0
    repository: https://fmontezuma.github.io/helm-chart/
  - name: polaris
    version: 0.1.4
    repository: https://fmontezuma.github.io/helm-chart
  - name: filebeat
    version: 0.1.4
    repository: https://fmontezuma.github.io/helm-chart/
  - name: apm
    version: 0.1.0
    repository: https://fmontezuma.github.io/helm-chart/
  - name: metricbeat
    version: 0.1.4
    repository: https://fmontezuma.github.io/helm-chart/
  - name: overprovisioner
    version: 0.1.3
    repository: https://fmontezuma.github.io/helm-chart/
  - name: kube-resource-report
    version: 0.1.3
    repository: https://fmontezuma.github.io/helm-chart/
  - name: heartbeat
    version: 0.1.4
    repository: https://fmontezuma.github.io/helm-chart/
