global:
  dnsSuffix: "test.local"
  namespace: default

minReplicas: 1
maxReplicas: 1
targetCPU: 60

resources:
  requests:
    memory: 200Mi
    cpu: "20m"
  limits:
    memory: 200Mi
    cpu: "400m"

config: |-
  logLevel = "INFO"
  defaultEntryPoints = ["http"]
  [entryPoints]
  [entryPoints.http]
  address = ":80"
  [api]    
  [file]
  [frontends]
  [backends]
  