{{- if eq .Values.dependenciesOnly false }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.appName }}
  namespace: {{ .Values.global.namespace }}
  annotations:
    currentDate: {{ now }}
  labels:
    app: {{ .Values.global.appName }}
spec:
  #replicas: {{ .Values.replicaCount }}
  progressDeadlineSeconds: {{ .Values.progressDeadlineSeconds }}
  selector:
    matchLabels:
      app: {{ .Values.global.appName }}
  template:
    metadata:
      annotations:
        currentDate: {{ now }}
      labels:
        app: {{ .Values.global.appName }}
    spec:
      containers:
        - name: {{ .Values.global.appName }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
            {{- with .Values.service.additionalPorts }}
              {{- toYaml .Values.service.additionalPorts | nindent 12 }}
            {{- end }}
          livenessProbe: {{ tpl .Values.livenessProbe . | nindent 12 }}
          readinessProbe: {{ tpl .Values.readinessProbe . | nindent 12 }}
          {{- with .Values.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.environmentVariables }}
          env:
          {{- range $k, $v := . }}
          - name: {{ quote $k }}
            value: {{ quote $v }}
          {{- end }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      affinity: {{ tpl .Values.affinity . | nindent 8 }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
{{- end }}