kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.global.appName }}
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    app: {{ .Values.global.appName }}
  ports:
  - protocol: "TCP"
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    name: {{ .Values.service.protocol }}-{{ .Values.global.appName }}
  {{- with .Values.service.additionalPorts }}
    {{- toYaml .Values.service.additionalPorts | nindent 2 }}
  {{- end }}
