{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.appName }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  - host: {{ .Values.appName }}-{{ .Values.namespace }}{{ .Values.global.dnsSuffix }}
    http:
      paths:
      - backend:
          serviceName: {{ .Values.appName }}
          servicePort: {{ .Values.service.port }}
  {{- with .Values.ingress.additionalRules }}
    {{- toYaml .Values.ingress.additionalRules | nindent 2 }}
  {{- end }}
{{- end }}
